/*!
 * @file achievement-definitions.cpp
 * @brief 実績定義データベースの実装
 * @date 2025/11/26
 * @author deskull
 */

#include "achievement/achievement-definitions.h"

using AD = AchievementDefinition;
using AT = AchievementType;
using AC = AchievementCategory;
using ADiff = AchievementDifficulty;

const std::map<AchievementType, std::shared_ptr<AchievementDefinition>> achievement_definitions = {
    // 探索系
    { AT::FIRST_DUNGEON_ENTRY,
        std::make_shared<AD>(
            AT::FIRST_DUNGEON_ENTRY,
            "初めてのダンジョン",
            "First Dungeon",
            "初めてダンジョンに足を踏み入れた",
            "Entered a dungeon for the first time",
            AC::EXPLORATION,
            ADiff::TRIVIAL,
            5) },

    { AT::REACH_DEPTH_10,
        std::make_shared<AD>(
            AT::REACH_DEPTH_10,
            "浅層探索者",
            "Shallow Explorer",
            "地下10階に到達した",
            "Reached dungeon level 10",
            AC::EXPLORATION,
            ADiff::EASY,
            10) },

    { AT::REACH_DEPTH_50,
        std::make_shared<AD>(
            AT::REACH_DEPTH_50,
            "中層探索者",
            "Intermediate Explorer",
            "地下50階に到達した",
            "Reached dungeon level 50",
            AC::EXPLORATION,
            ADiff::NORMAL,
            25) },

    { AT::REACH_DEPTH_100,
        std::make_shared<AD>(
            AT::REACH_DEPTH_100,
            "深淵の探索者",
            "Deep Explorer",
            "地下100階に到達した",
            "Reached dungeon level 100",
            AC::EXPLORATION,
            ADiff::HARD,
            50) },

    // 戦闘系
    { AT::FIRST_KILL,
        std::make_shared<AD>(
            AT::FIRST_KILL,
            "初めての勝利",
            "First Victory",
            "初めてモンスターを倒した",
            "Defeated your first monster",
            AC::COMBAT,
            ADiff::TRIVIAL,
            5) },

    { AT::KILL_100_MONSTERS,
        std::make_shared<AD>(
            AT::KILL_100_MONSTERS,
            "駆け出しハンター",
            "Novice Hunter",
            "100体のモンスターを倒した",
            "Defeated 100 monsters",
            AC::COMBAT,
            ADiff::EASY,
            10) },

    { AT::KILL_1000_MONSTERS,
        std::make_shared<AD>(
            AT::KILL_1000_MONSTERS,
            "ベテランハンター",
            "Veteran Hunter",
            "1000体のモンスターを倒した",
            "Defeated 1000 monsters",
            AC::COMBAT,
            ADiff::NORMAL,
            30) },

    { AT::KILL_FIRST_UNIQUE,
        std::make_shared<AD>(
            AT::KILL_FIRST_UNIQUE,
            "伝説への第一歩",
            "First Legend",
            "初めてユニークモンスターを倒した",
            "Defeated your first unique monster",
            AC::COMBAT,
            ADiff::EASY,
            15) },

    // レベル系
    { AT::REACH_LEVEL_10,
        std::make_shared<AD>(
            AT::REACH_LEVEL_10,
            "駆け出し冒険者",
            "Beginner Adventurer",
            "レベル10に到達した",
            "Reached level 10",
            AC::CHARACTER,
            ADiff::TRIVIAL,
            5) },

    { AT::REACH_LEVEL_25,
        std::make_shared<AD>(
            AT::REACH_LEVEL_25,
            "熟練冒険者",
            "Skilled Adventurer",
            "レベル25に到達した",
            "Reached level 25",
            AC::CHARACTER,
            ADiff::EASY,
            15) },

    { AT::REACH_LEVEL_50,
        std::make_shared<AD>(
            AT::REACH_LEVEL_50,
            "伝説の冒険者",
            "Legendary Adventurer",
            "レベル50に到達した",
            "Reached level 50",
            AC::CHARACTER,
            ADiff::HARD,
            50) },

    // 職業レベル到達系
    // レベル5（称号2段階目）
    { AT::WARRIOR_TITLE_L5,
        std::make_shared<AD>(
            AT::WARRIOR_TITLE_L5,
            "兵士",
            "Soldier",
            "戦士としてレベル5に到達した",
            "Reached level 5 as Warrior",
            AC::CHARACTER,
            ADiff::TRIVIAL,
            5) },

    { AT::MAGE_TITLE_L5,
        std::make_shared<AD>(
            AT::MAGE_TITLE_L5,
            "奇術師",
            "Trickster",
            "メイジとしてレベル5に到達した",
            "Reached level 5 as Mage",
            AC::CHARACTER,
            ADiff::TRIVIAL,
            5) },

    { AT::PRIEST_TITLE_L5,
        std::make_shared<AD>(
            AT::PRIEST_TITLE_L5,
            "聖徒",
            "Acolyte",
            "プリーストとしてレベル5に到達した",
            "Reached level 5 as Priest",
            AC::CHARACTER,
            ADiff::TRIVIAL,
            5) },

    { AT::ROGUE_TITLE_L5,
        std::make_shared<AD>(
            AT::ROGUE_TITLE_L5,
            "追いはぎ",
            "Robber",
            "盗賊としてレベル5に到達した",
            "Reached level 5 as Rogue",
            AC::CHARACTER,
            ADiff::TRIVIAL,
            5) },

    { AT::RANGER_TITLE_L5,
        std::make_shared<AD>(
            AT::RANGER_TITLE_L5,
            "馳夫",
            "Strider",
            "レンジャーとしてレベル5に到達した",
            "Reached level 5 as Ranger",
            AC::CHARACTER,
            ADiff::TRIVIAL,
            5) },

    { AT::PALADIN_TITLE_L5,
        std::make_shared<AD>(
            AT::PALADIN_TITLE_L5,
            "ガードマン",
            "Guardsman",
            "パラディンとしてレベル5に到達した",
            "Reached level 5 as Paladin",
            AC::CHARACTER,
            ADiff::TRIVIAL,
            5) },

    { AT::WARRIOR_MAGE_TITLE_L5,
        std::make_shared<AD>(
            AT::WARRIOR_MAGE_TITLE_L5,
            "徒弟",
            "Apprentice",
            "魔法戦士としてレベル5に到達した",
            "Reached level 5 as Warrior-Mage",
            AC::CHARACTER,
            ADiff::TRIVIAL,
            5) },

    { AT::CHAOS_WARRIOR_TITLE_L5,
        std::make_shared<AD>(
            AT::CHAOS_WARRIOR_TITLE_L5,
            "兵士",
            "Soldier",
            "混沌の戦士としてレベル5に到達した",
            "Reached level 5 as Chaos-Warrior",
            AC::CHARACTER,
            ADiff::TRIVIAL,
            5) },

    { AT::MONK_TITLE_L5,
        std::make_shared<AD>(
            AT::MONK_TITLE_L5,
            "弟子",
            "Brother",
            "修行僧としてレベル5に到達した",
            "Reached level 5 as Monk",
            AC::CHARACTER,
            ADiff::TRIVIAL,
            5) },

    { AT::MINDCRAFTER_TITLE_L5,
        std::make_shared<AD>(
            AT::MINDCRAFTER_TITLE_L5,
            "オブザーバー",
            "Observer",
            "超能力者としてレベル5に到達した",
            "Reached level 5 as Mindcrafter",
            AC::CHARACTER,
            ADiff::TRIVIAL,
            5) },

    { AT::HIGH_MAGE_TITLE_L5,
        std::make_shared<AD>(
            AT::HIGH_MAGE_TITLE_L5,
            "奇術師",
            "Trickster",
            "ハイ=メイジとしてレベル5に到達した",
            "Reached level 5 as High-Mage",
            AC::CHARACTER,
            ADiff::TRIVIAL,
            5) },

    { AT::TOURIST_TITLE_L5,
        std::make_shared<AD>(
            AT::TOURIST_TITLE_L5,
            "観光客",
            "Sightseer",
            "観光客としてレベル5に到達した",
            "Reached level 5 as Tourist",
            AC::CHARACTER,
            ADiff::TRIVIAL,
            5) },

    { AT::IMITATOR_TITLE_L5,
        std::make_shared<AD>(
            AT::IMITATOR_TITLE_L5,
            "らしくない",
            "not good",
            "ものまね師としてレベル5に到達した",
            "Reached level 5 as Imitator",
            AC::CHARACTER,
            ADiff::TRIVIAL,
            5) },

    { AT::BEASTMASTER_TITLE_L5,
        std::make_shared<AD>(
            AT::BEASTMASTER_TITLE_L5,
            "ウルフ使い",
            "Wolf Master",
            "魔獣使いとしてレベル5に到達した",
            "Reached level 5 as BeastMaster",
            AC::CHARACTER,
            ADiff::TRIVIAL,
            5) },

    { AT::SORCERER_TITLE_L5,
        std::make_shared<AD>(
            AT::SORCERER_TITLE_L5,
            "奇術師",
            "Trickster",
            "スペルマスターとしてレベル5に到達した",
            "Reached level 5 as Sorcerer",
            AC::CHARACTER,
            ADiff::TRIVIAL,
            5) },

    { AT::ARCHER_TITLE_L5,
        std::make_shared<AD>(
            AT::ARCHER_TITLE_L5,
            "兵士",
            "Soldier",
            "アーチャーとしてレベル5に到達した",
            "Reached level 5 as Archer",
            AC::CHARACTER,
            ADiff::TRIVIAL,
            5) },

    { AT::MAGIC_EATER_TITLE_L5,
        std::make_shared<AD>(
            AT::MAGIC_EATER_TITLE_L5,
            "入門者",
            "Beginner",
            "魔道具術師としてレベル5に到達した",
            "Reached level 5 as Magic-Eater",
            AC::CHARACTER,
            ADiff::TRIVIAL,
            5) },

    { AT::BARD_TITLE_L5,
        std::make_shared<AD>(
            AT::BARD_TITLE_L5,
            "作曲家",
            "Songsmith",
            "吟遊詩人としてレベル5に到達した",
            "Reached level 5 as Bard",
            AC::CHARACTER,
            ADiff::TRIVIAL,
            5) },

    { AT::RED_MAGE_TITLE_L5,
        std::make_shared<AD>(
            AT::RED_MAGE_TITLE_L5,
            "徒弟",
            "Apprentice",
            "赤魔道師としてレベル5に到達した",
            "Reached level 5 as Red-Mage",
            AC::CHARACTER,
            ADiff::TRIVIAL,
            5) },

    { AT::SAMURAI_TITLE_L5,
        std::make_shared<AD>(
            AT::SAMURAI_TITLE_L5,
            "弟子",
            "Brother",
            "剣術家としてレベル5に到達した",
            "Reached level 5 as Samurai",
            AC::CHARACTER,
            ADiff::TRIVIAL,
            5) },

    { AT::FORCETRAINER_TITLE_L5,
        std::make_shared<AD>(
            AT::FORCETRAINER_TITLE_L5,
            "弟子",
            "Brother",
            "練気術師としてレベル5に到達した",
            "Reached level 5 as ForceTrainer",
            AC::CHARACTER,
            ADiff::TRIVIAL,
            5) },

    { AT::BLUE_MAGE_TITLE_L5,
        std::make_shared<AD>(
            AT::BLUE_MAGE_TITLE_L5,
            "奇術師",
            "Trickster",
            "青魔道師としてレベル5に到達した",
            "Reached level 5 as Blue-Mage",
            AC::CHARACTER,
            ADiff::TRIVIAL,
            5) },

    { AT::CAVALRY_TITLE_L5,
        std::make_shared<AD>(
            AT::CAVALRY_TITLE_L5,
            "兵士",
            "Soldier",
            "騎兵としてレベル5に到達した",
            "Reached level 5 as Cavalry",
            AC::CHARACTER,
            ADiff::TRIVIAL,
            5) },

    { AT::BERSERKER_TITLE_L5,
        std::make_shared<AD>(
            AT::BERSERKER_TITLE_L5,
            "バーサーカー",
            "Berserker",
            "狂戦士としてレベル5に到達した",
            "Reached level 5 as Berserker",
            AC::CHARACTER,
            ADiff::TRIVIAL,
            5) },

    { AT::SMITH_TITLE_L5,
        std::make_shared<AD>(
            AT::SMITH_TITLE_L5,
            "名無し",
            "Nameless",
            "鍛冶師としてレベル5に到達した",
            "Reached level 5 as Weaponsmith",
            AC::CHARACTER,
            ADiff::TRIVIAL,
            5) },

    { AT::MIRROR_MASTER_TITLE_L5,
        std::make_shared<AD>(
            AT::MIRROR_MASTER_TITLE_L5,
            "鏡職人",
            "Mirrormaker",
            "鏡使いとしてレベル5に到達した",
            "Reached level 5 as Mirror-Master",
            AC::CHARACTER,
            ADiff::TRIVIAL,
            5) },

    { AT::NINJA_TITLE_L5,
        std::make_shared<AD>(
            AT::NINJA_TITLE_L5,
            "仕手",
            "Myrmidon",
            "忍者としてレベル5に到達した",
            "Reached level 5 as Ninja",
            AC::CHARACTER,
            ADiff::TRIVIAL,
            5) },

    { AT::SNIPER_TITLE_L5,
        std::make_shared<AD>(
            AT::SNIPER_TITLE_L5,
            "兵士",
            "Soldier",
            "スナイパーとしてレベル5に到達した",
            "Reached level 5 as Sniper",
            AC::CHARACTER,
            ADiff::TRIVIAL,
            5) },

    { AT::ELEMENTALIST_TITLE_L5,
        std::make_shared<AD>(
            AT::ELEMENTALIST_TITLE_L5,
            "奇術師",
            "Trickster",
            "元素使いとしてレベル5に到達した",
            "Reached level 5 as Elementalist",
            AC::CHARACTER,
            ADiff::TRIVIAL,
            5) },

    // レベル10（称号3段階目）
    { AT::WARRIOR_TITLE_L10,
        std::make_shared<AD>(
            AT::WARRIOR_TITLE_L10,
            "傭兵",
            "Mercenary",
            "戦士としてレベル10に到達した",
            "Reached level 10 as Warrior",
            AC::CHARACTER,
            ADiff::EASY,
            10) },

    { AT::MAGE_TITLE_L10,
        std::make_shared<AD>(
            AT::MAGE_TITLE_L10,
            "幻術師",
            "Illusionist",
            "メイジとしてレベル10に到達した",
            "Reached level 10 as Mage",
            AC::CHARACTER,
            ADiff::EASY,
            10) },

    { AT::PRIEST_TITLE_L10,
        std::make_shared<AD>(
            AT::PRIEST_TITLE_L10,
            "アデプト",
            "Adept",
            "プリーストとしてレベル10に到達した",
            "Reached level 10 as Priest",
            AC::CHARACTER,
            ADiff::EASY,
            10) },

    { AT::ROGUE_TITLE_L10,
        std::make_shared<AD>(
            AT::ROGUE_TITLE_L10,
            "夜盗",
            "Burglar",
            "盗賊としてレベル10に到達した",
            "Reached level 10 as Rogue",
            AC::CHARACTER,
            ADiff::EASY,
            10) },

    { AT::RANGER_TITLE_L10,
        std::make_shared<AD>(
            AT::RANGER_TITLE_L10,
            "斥候",
            "Scout",
            "レンジャーとしてレベル10に到達した",
            "Reached level 10 as Ranger",
            AC::CHARACTER,
            ADiff::EASY,
            10) },

    { AT::PALADIN_TITLE_L10,
        std::make_shared<AD>(
            AT::PALADIN_TITLE_L10,
            "見習い騎士",
            "Knight Errant",
            "パラディンとしてレベル10に到達した",
            "Reached level 10 as Paladin",
            AC::CHARACTER,
            ADiff::EASY,
            10) },

    { AT::WARRIOR_MAGE_TITLE_L10,
        std::make_shared<AD>(
            AT::WARRIOR_MAGE_TITLE_L10,
            "一人前",
            "Journeyman",
            "魔法戦士としてレベル10に到達した",
            "Reached level 10 as Warrior-Mage",
            AC::CHARACTER,
            ADiff::EASY,
            10) },

    { AT::CHAOS_WARRIOR_TITLE_L10,
        std::make_shared<AD>(
            AT::CHAOS_WARRIOR_TITLE_L10,
            "傭兵",
            "Mercenary",
            "混沌の戦士としてレベル10に到達した",
            "Reached level 10 as Chaos-Warrior",
            AC::CHARACTER,
            ADiff::EASY,
            10) },

    { AT::MONK_TITLE_L10,
        std::make_shared<AD>(
            AT::MONK_TITLE_L10,
            "直弟子",
            "Disciple",
            "修行僧としてレベル10に到達した",
            "Reached level 10 as Monk",
            AC::CHARACTER,
            ADiff::EASY,
            10) },

    { AT::MINDCRAFTER_TITLE_L10,
        std::make_shared<AD>(
            AT::MINDCRAFTER_TITLE_L10,
            "シーア",
            "Seer",
            "超能力者としてレベル10に到達した",
            "Reached level 10 as Mindcrafter",
            AC::CHARACTER,
            ADiff::EASY,
            10) },

    { AT::HIGH_MAGE_TITLE_L10,
        std::make_shared<AD>(
            AT::HIGH_MAGE_TITLE_L10,
            "幻術師",
            "Illusionist",
            "ハイ=メイジとしてレベル10に到達した",
            "Reached level 10 as High-Mage",
            AC::CHARACTER,
            ADiff::EASY,
            10) },

    { AT::TOURIST_TITLE_L10,
        std::make_shared<AD>(
            AT::TOURIST_TITLE_L10,
            "周遊旅行者",
            "Excursionist",
            "観光客としてレベル10に到達した",
            "Reached level 10 as Tourist",
            AC::CHARACTER,
            ADiff::EASY,
            10) },

    { AT::IMITATOR_TITLE_L10,
        std::make_shared<AD>(
            AT::IMITATOR_TITLE_L10,
            "まあまあ",
            "not bad",
            "ものまね師としてレベル10に到達した",
            "Reached level 10 as Imitator",
            AC::CHARACTER,
            ADiff::EASY,
            10) },

    { AT::BEASTMASTER_TITLE_L10,
        std::make_shared<AD>(
            AT::BEASTMASTER_TITLE_L10,
            "クモ使い",
            "Spider Master",
            "魔獣使いとしてレベル10に到達した",
            "Reached level 10 as BeastMaster",
            AC::CHARACTER,
            ADiff::EASY,
            10) },

    { AT::SORCERER_TITLE_L10,
        std::make_shared<AD>(
            AT::SORCERER_TITLE_L10,
            "幻術師",
            "Illusionist",
            "スペルマスターとしてレベル10に到達した",
            "Reached level 10 as Sorcerer",
            AC::CHARACTER,
            ADiff::EASY,
            10) },

    { AT::ARCHER_TITLE_L10,
        std::make_shared<AD>(
            AT::ARCHER_TITLE_L10,
            "傭兵",
            "Mercenary",
            "アーチャーとしてレベル10に到達した",
            "Reached level 10 as Archer",
            AC::CHARACTER,
            ADiff::EASY,
            10) },

    { AT::MAGIC_EATER_TITLE_L10,
        std::make_shared<AD>(
            AT::MAGIC_EATER_TITLE_L10,
            "奇術師",
            "Jagguler",
            "魔道具術師としてレベル10に到達した",
            "Reached level 10 as Magic-Eater",
            AC::CHARACTER,
            ADiff::EASY,
            10) },

    { AT::BARD_TITLE_L10,
        std::make_shared<AD>(
            AT::BARD_TITLE_L10,
            "吟遊詩人",
            "Bard",
            "吟遊詩人としてレベル10に到達した",
            "Reached level 10 as Bard",
            AC::CHARACTER,
            ADiff::EASY,
            10) },

    { AT::RED_MAGE_TITLE_L10,
        std::make_shared<AD>(
            AT::RED_MAGE_TITLE_L10,
            "一人前",
            "Journeyman",
            "赤魔道師としてレベル10に到達した",
            "Reached level 10 as Red-Mage",
            AC::CHARACTER,
            ADiff::EASY,
            10) },

    { AT::SAMURAI_TITLE_L10,
        std::make_shared<AD>(
            AT::SAMURAI_TITLE_L10,
            "直弟子",
            "Disciple",
            "剣術家としてレベル10に到達した",
            "Reached level 10 as Samurai",
            AC::CHARACTER,
            ADiff::EASY,
            10) },

    { AT::FORCETRAINER_TITLE_L10,
        std::make_shared<AD>(
            AT::FORCETRAINER_TITLE_L10,
            "直弟子",
            "Disciple",
            "練気術師としてレベル10に到達した",
            "Reached level 10 as ForceTrainer",
            AC::CHARACTER,
            ADiff::EASY,
            10) },

    { AT::BLUE_MAGE_TITLE_L10,
        std::make_shared<AD>(
            AT::BLUE_MAGE_TITLE_L10,
            "幻術師",
            "Illusionist",
            "青魔道師としてレベル10に到達した",
            "Reached level 10 as Blue-Mage",
            AC::CHARACTER,
            ADiff::EASY,
            10) },

    { AT::CAVALRY_TITLE_L10,
        std::make_shared<AD>(
            AT::CAVALRY_TITLE_L10,
            "傭兵",
            "Mercenary",
            "騎兵としてレベル10に到達した",
            "Reached level 10 as Cavalry",
            AC::CHARACTER,
            ADiff::EASY,
            10) },

    { AT::BERSERKER_TITLE_L10,
        std::make_shared<AD>(
            AT::BERSERKER_TITLE_L10,
            "バーサーカー",
            "Berserker",
            "狂戦士としてレベル10に到達した",
            "Reached level 10 as Berserker",
            AC::CHARACTER,
            ADiff::EASY,
            10) },

    { AT::SMITH_TITLE_L10,
        std::make_shared<AD>(
            AT::SMITH_TITLE_L10,
            "名も無き者",
            "Nameless one",
            "鍛冶師としてレベル10に到達した",
            "Reached level 10 as Weaponsmith",
            AC::CHARACTER,
            ADiff::EASY,
            10) },

    { AT::MIRROR_MASTER_TITLE_L10,
        std::make_shared<AD>(
            AT::MIRROR_MASTER_TITLE_L10,
            "鏡職人",
            "Mirrormaker",
            "鏡使いとしてレベル10に到達した",
            "Reached level 10 as Mirror-Master",
            AC::CHARACTER,
            ADiff::EASY,
            10) },

    { AT::NINJA_TITLE_L10,
        std::make_shared<AD>(
            AT::NINJA_TITLE_L10,
            "熟達者",
            "Initiate",
            "忍者としてレベル10に到達した",
            "Reached level 10 as Ninja",
            AC::CHARACTER,
            ADiff::EASY,
            10) },

    { AT::SNIPER_TITLE_L10,
        std::make_shared<AD>(
            AT::SNIPER_TITLE_L10,
            "傭兵",
            "Mercenary",
            "スナイパーとしてレベル10に到達した",
            "Reached level 10 as Sniper",
            AC::CHARACTER,
            ADiff::EASY,
            10) },

    { AT::ELEMENTALIST_TITLE_L10,
        std::make_shared<AD>(
            AT::ELEMENTALIST_TITLE_L10,
            "幻術師",
            "Illusionist",
            "元素使いとしてレベル10に到達した",
            "Reached level 10 as Elementalist",
            AC::CHARACTER,
            ADiff::EASY,
            10) },

    // レベル15（称号4段階目）
    { AT::WARRIOR_TITLE_L15,
        std::make_shared<AD>(
            AT::WARRIOR_TITLE_L15,
            "古参兵",
            "Veteran",
            "戦士としてレベル15に到達した",
            "Reached level 15 as Warrior",
            AC::CHARACTER,
            ADiff::EASY,
            15) },

    { AT::MAGE_TITLE_L15,
        std::make_shared<AD>(
            AT::MAGE_TITLE_L15,
            "呪術師",
            "Spellbinder",
            "メイジとしてレベル15に到達した",
            "Reached level 15 as Mage",
            AC::CHARACTER,
            ADiff::EASY,
            15) },

    { AT::PRIEST_TITLE_L15,
        std::make_shared<AD>(
            AT::PRIEST_TITLE_L15,
            "牧師",
            "Priest",
            "プリーストとしてレベル15に到達した",
            "Reached level 15 as Priest",
            AC::CHARACTER,
            ADiff::EASY,
            15) },

    { AT::ROGUE_TITLE_L15,
        std::make_shared<AD>(
            AT::ROGUE_TITLE_L15,
            "こそ泥",
            "Filcher",
            "盗賊としてレベル15に到達した",
            "Reached level 15 as Rogue",
            AC::CHARACTER,
            ADiff::EASY,
            15) },

    { AT::RANGER_TITLE_L15,
        std::make_shared<AD>(
            AT::RANGER_TITLE_L15,
            "狩人",
            "Courser",
            "レンジャーとしてレベル15に到達した",
            "Reached level 15 as Ranger",
            AC::CHARACTER,
            ADiff::EASY,
            15) },

    { AT::PALADIN_TITLE_L15,
        std::make_shared<AD>(
            AT::PALADIN_TITLE_L15,
            "パラディン",
            "Companion",
            "パラディンとしてレベル15に到達した",
            "Reached level 15 as Paladin",
            AC::CHARACTER,
            ADiff::EASY,
            15) },

    { AT::WARRIOR_MAGE_TITLE_L15,
        std::make_shared<AD>(
            AT::WARRIOR_MAGE_TITLE_L15,
            "古参兵",
            "Veteran",
            "魔法戦士としてレベル15に到達した",
            "Reached level 15 as Warrior-Mage",
            AC::CHARACTER,
            ADiff::EASY,
            15) },

    { AT::CHAOS_WARRIOR_TITLE_L15,
        std::make_shared<AD>(
            AT::CHAOS_WARRIOR_TITLE_L15,
            "古参兵",
            "Veteran",
            "混沌の戦士としてレベル15に到達した",
            "Reached level 15 as Chaos-Warrior",
            AC::CHARACTER,
            ADiff::EASY,
            15) },

    { AT::MONK_TITLE_L15,
        std::make_shared<AD>(
            AT::MONK_TITLE_L15,
            "師範代",
            "Immaculate",
            "修行僧としてレベル15に到達した",
            "Reached level 15 as Monk",
            AC::CHARACTER,
            ADiff::EASY,
            15) },

    { AT::MINDCRAFTER_TITLE_L15,
        std::make_shared<AD>(
            AT::MINDCRAFTER_TITLE_L15,
            "セージ",
            "Sage",
            "超能力者としてレベル15に到達した",
            "Reached level 15 as Mindcrafter",
            AC::CHARACTER,
            ADiff::EASY,
            15) },

    { AT::HIGH_MAGE_TITLE_L15,
        std::make_shared<AD>(
            AT::HIGH_MAGE_TITLE_L15,
            "呪術師",
            "Spellbinder",
            "ハイ=メイジとしてレベル15に到達した",
            "Reached level 15 as High-Mage",
            AC::CHARACTER,
            ADiff::EASY,
            15) },

    { AT::TOURIST_TITLE_L15,
        std::make_shared<AD>(
            AT::TOURIST_TITLE_L15,
            "遍歴者",
            "Peregrinator",
            "観光客としてレベル15に到達した",
            "Reached level 15 as Tourist",
            AC::CHARACTER,
            ADiff::EASY,
            15) },

    { AT::IMITATOR_TITLE_L15,
        std::make_shared<AD>(
            AT::IMITATOR_TITLE_L15,
            "まあまあかな",
            "good",
            "ものまね師としてレベル15に到達した",
            "Reached level 15 as Imitator",
            AC::CHARACTER,
            ADiff::EASY,
            15) },

    { AT::BEASTMASTER_TITLE_L15,
        std::make_shared<AD>(
            AT::BEASTMASTER_TITLE_L15,
            "ヒドラ使い",
            "Hydra Master",
            "魔獣使いとしてレベル15に到達した",
            "Reached level 15 as BeastMaster",
            AC::CHARACTER,
            ADiff::EASY,
            15) },

    { AT::SORCERER_TITLE_L15,
        std::make_shared<AD>(
            AT::SORCERER_TITLE_L15,
            "呪術師",
            "Spellbinder",
            "スペルマスターとしてレベル15に到達した",
            "Reached level 15 as Sorcerer",
            AC::CHARACTER,
            ADiff::EASY,
            15) },

    { AT::ARCHER_TITLE_L15,
        std::make_shared<AD>(
            AT::ARCHER_TITLE_L15,
            "古参兵",
            "Veteran",
            "アーチャーとしてレベル15に到達した",
            "Reached level 15 as Archer",
            AC::CHARACTER,
            ADiff::EASY,
            15) },

    { AT::MAGIC_EATER_TITLE_L15,
        std::make_shared<AD>(
            AT::MAGIC_EATER_TITLE_L15,
            "秘術師",
            "Skilled",
            "魔道具術師としてレベル15に到達した",
            "Reached level 15 as Magic-Eater",
            AC::CHARACTER,
            ADiff::EASY,
            15) },

    { AT::BARD_TITLE_L15,
        std::make_shared<AD>(
            AT::BARD_TITLE_L15,
            "コンパニオン",
            "Companion",
            "吟遊詩人としてレベル15に到達した",
            "Reached level 15 as Bard",
            AC::CHARACTER,
            ADiff::EASY,
            15) },

    { AT::RED_MAGE_TITLE_L15,
        std::make_shared<AD>(
            AT::RED_MAGE_TITLE_L15,
            "古参兵",
            "Veteran",
            "赤魔道師としてレベル15に到達した",
            "Reached level 15 as Red-Mage",
            AC::CHARACTER,
            ADiff::EASY,
            15) },

    { AT::SAMURAI_TITLE_L15,
        std::make_shared<AD>(
            AT::SAMURAI_TITLE_L15,
            "師範代",
            "Immaculate",
            "剣術家としてレベル15に到達した",
            "Reached level 15 as Samurai",
            AC::CHARACTER,
            ADiff::EASY,
            15) },

    { AT::FORCETRAINER_TITLE_L15,
        std::make_shared<AD>(
            AT::FORCETRAINER_TITLE_L15,
            "師範代",
            "Immaculate",
            "練気術師としてレベル15に到達した",
            "Reached level 15 as ForceTrainer",
            AC::CHARACTER,
            ADiff::EASY,
            15) },

    { AT::BLUE_MAGE_TITLE_L15,
        std::make_shared<AD>(
            AT::BLUE_MAGE_TITLE_L15,
            "呪術師",
            "Spellbinder",
            "青魔道師としてレベル15に到達した",
            "Reached level 15 as Blue-Mage",
            AC::CHARACTER,
            ADiff::EASY,
            15) },

    { AT::CAVALRY_TITLE_L15,
        std::make_shared<AD>(
            AT::CAVALRY_TITLE_L15,
            "古参兵",
            "Veteran",
            "騎兵としてレベル15に到達した",
            "Reached level 15 as Cavalry",
            AC::CHARACTER,
            ADiff::EASY,
            15) },

    { AT::BERSERKER_TITLE_L15,
        std::make_shared<AD>(
            AT::BERSERKER_TITLE_L15,
            "バーサーカー",
            "Berserker",
            "狂戦士としてレベル15に到達した",
            "Reached level 15 as Berserker",
            AC::CHARACTER,
            ADiff::EASY,
            15) },

    { AT::SMITH_TITLE_L15,
        std::make_shared<AD>(
            AT::SMITH_TITLE_L15,
            "鍛えたる者",
            "One Who Forges",
            "鍛冶師としてレベル15に到達した",
            "Reached level 15 as Weaponsmith",
            AC::CHARACTER,
            ADiff::EASY,
            15) },

    { AT::MIRROR_MASTER_TITLE_L15,
        std::make_shared<AD>(
            AT::MIRROR_MASTER_TITLE_L15,
            "鏡師匠",
            "Mirror Master",
            "鏡使いとしてレベル15に到達した",
            "Reached level 15 as Mirror-Master",
            AC::CHARACTER,
            ADiff::EASY,
            15) },

    { AT::NINJA_TITLE_L15,
        std::make_shared<AD>(
            AT::NINJA_TITLE_L15,
            "短刀使い",
            "Knifer",
            "忍者としてレベル15に到達した",
            "Reached level 15 as Ninja",
            AC::CHARACTER,
            ADiff::EASY,
            15) },

    { AT::SNIPER_TITLE_L15,
        std::make_shared<AD>(
            AT::SNIPER_TITLE_L15,
            "古参兵",
            "Veteran",
            "スナイパーとしてレベル15に到達した",
            "Reached level 15 as Sniper",
            AC::CHARACTER,
            ADiff::EASY,
            15) },

    { AT::ELEMENTALIST_TITLE_L15,
        std::make_shared<AD>(
            AT::ELEMENTALIST_TITLE_L15,
            "呪術師",
            "Spellbinder",
            "元素使いとしてレベル15に到達した",
            "Reached level 15 as Elementalist",
            AC::CHARACTER,
            ADiff::EASY,
            15) },

    // レベル20（称号5段階目）
    { AT::WARRIOR_TITLE_L20,
        std::make_shared<AD>(
            AT::WARRIOR_TITLE_L20,
            "古参兵",
            "Veteran",
            "戦士としてレベル20に到達した",
            "Reached level 20 as Warrior",
            AC::CHARACTER,
            ADiff::NORMAL,
            20) },

    { AT::MAGE_TITLE_L20,
        std::make_shared<AD>(
            AT::MAGE_TITLE_L20,
            "呪術師",
            "Spellbinder",
            "メイジとしてレベル20に到達した",
            "Reached level 20 as Mage",
            AC::CHARACTER,
            ADiff::NORMAL,
            20) },

    { AT::PRIEST_TITLE_L20,
        std::make_shared<AD>(
            AT::PRIEST_TITLE_L20,
            "聖職者",
            "Curate",
            "プリーストとしてレベル20に到達した",
            "Reached level 20 as Priest",
            AC::CHARACTER,
            ADiff::NORMAL,
            20) },

    { AT::ROGUE_TITLE_L20,
        std::make_shared<AD>(
            AT::ROGUE_TITLE_L20,
            "こそ泥",
            "Filcher",
            "盗賊としてレベル20に到達した",
            "Reached level 20 as Rogue",
            AC::CHARACTER,
            ADiff::NORMAL,
            20) },

    { AT::RANGER_TITLE_L20,
        std::make_shared<AD>(
            AT::RANGER_TITLE_L20,
            "狩人",
            "Courser",
            "レンジャーとしてレベル20に到達した",
            "Reached level 20 as Ranger",
            AC::CHARACTER,
            ADiff::NORMAL,
            20) },

    { AT::PALADIN_TITLE_L20,
        std::make_shared<AD>(
            AT::PALADIN_TITLE_L20,
            "防衛者",
            "Defender",
            "パラディンとしてレベル20に到達した",
            "Reached level 20 as Paladin",
            AC::CHARACTER,
            ADiff::NORMAL,
            20) },

    { AT::WARRIOR_MAGE_TITLE_L20,
        std::make_shared<AD>(
            AT::WARRIOR_MAGE_TITLE_L20,
            "古参兵",
            "Veteran",
            "魔法戦士としてレベル20に到達した",
            "Reached level 20 as Warrior-Mage",
            AC::CHARACTER,
            ADiff::NORMAL,
            20) },

    { AT::CHAOS_WARRIOR_TITLE_L20,
        std::make_shared<AD>(
            AT::CHAOS_WARRIOR_TITLE_L20,
            "古参兵",
            "Veteran",
            "混沌の戦士としてレベル20に到達した",
            "Reached level 20 as Chaos-Warrior",
            AC::CHARACTER,
            ADiff::NORMAL,
            20) },

    { AT::MONK_TITLE_L20,
        std::make_shared<AD>(
            AT::MONK_TITLE_L20,
            "師範代",
            "Immaculate",
            "修行僧としてレベル20に到達した",
            "Reached level 20 as Monk",
            AC::CHARACTER,
            ADiff::NORMAL,
            20) },

    { AT::MINDCRAFTER_TITLE_L20,
        std::make_shared<AD>(
            AT::MINDCRAFTER_TITLE_L20,
            "熟達士",
            "Immaculate",
            "超能力者としてレベル20に到達した",
            "Reached level 20 as Mindcrafter",
            AC::CHARACTER,
            ADiff::NORMAL,
            20) },

    { AT::HIGH_MAGE_TITLE_L20,
        std::make_shared<AD>(
            AT::HIGH_MAGE_TITLE_L20,
            "呪術師",
            "Spellbinder",
            "ハイ=メイジとしてレベル20に到達した",
            "Reached level 20 as High-Mage",
            AC::CHARACTER,
            ADiff::NORMAL,
            20) },

    { AT::TOURIST_TITLE_L20,
        std::make_shared<AD>(
            AT::TOURIST_TITLE_L20,
            "遍歴者",
            "Peregrinator",
            "観光客としてレベル20に到達した",
            "Reached level 20 as Tourist",
            AC::CHARACTER,
            ADiff::NORMAL,
            20) },

    { AT::IMITATOR_TITLE_L20,
        std::make_shared<AD>(
            AT::IMITATOR_TITLE_L20,
            "ぼちぼち",
            "So so",
            "ものまね師としてレベル20に到達した",
            "Reached level 20 as Imitator",
            AC::CHARACTER,
            ADiff::NORMAL,
            20) },

    { AT::BEASTMASTER_TITLE_L20,
        std::make_shared<AD>(
            AT::BEASTMASTER_TITLE_L20,
            "狼使い",
            "Wolf Master",
            "魔獣使いとしてレベル20に到達した",
            "Reached level 20 as BeastMaster",
            AC::CHARACTER,
            ADiff::NORMAL,
            20) },

    { AT::SORCERER_TITLE_L20,
        std::make_shared<AD>(
            AT::SORCERER_TITLE_L20,
            "呪術師",
            "Spellbinder",
            "スペルマスターとしてレベル20に到達した",
            "Reached level 20 as Sorcerer",
            AC::CHARACTER,
            ADiff::NORMAL,
            20) },

    { AT::ARCHER_TITLE_L20,
        std::make_shared<AD>(
            AT::ARCHER_TITLE_L20,
            "古参兵",
            "Veteran",
            "アーチャーとしてレベル20に到達した",
            "Reached level 20 as Archer",
            AC::CHARACTER,
            ADiff::NORMAL,
            20) },

    { AT::MAGIC_EATER_TITLE_L20,
        std::make_shared<AD>(
            AT::MAGIC_EATER_TITLE_L20,
            "秘術師",
            "Skilled",
            "魔道具術師としてレベル20に到達した",
            "Reached level 20 as Magic-Eater",
            AC::CHARACTER,
            ADiff::NORMAL,
            20) },

    { AT::BARD_TITLE_L20,
        std::make_shared<AD>(
            AT::BARD_TITLE_L20,
            "コンパニオン",
            "Companion",
            "吟遊詩人としてレベル20に到達した",
            "Reached level 20 as Bard",
            AC::CHARACTER,
            ADiff::NORMAL,
            20) },

    { AT::RED_MAGE_TITLE_L20,
        std::make_shared<AD>(
            AT::RED_MAGE_TITLE_L20,
            "古参兵",
            "Veteran",
            "赤魔道師としてレベル20に到達した",
            "Reached level 20 as Red-Mage",
            AC::CHARACTER,
            ADiff::NORMAL,
            20) },

    { AT::SAMURAI_TITLE_L20,
        std::make_shared<AD>(
            AT::SAMURAI_TITLE_L20,
            "師範代",
            "Immaculate",
            "剣術家としてレベル20に到達した",
            "Reached level 20 as Samurai",
            AC::CHARACTER,
            ADiff::NORMAL,
            20) },

    { AT::FORCETRAINER_TITLE_L20,
        std::make_shared<AD>(
            AT::FORCETRAINER_TITLE_L20,
            "師範代",
            "Immaculate",
            "練気術師としてレベル20に到達した",
            "Reached level 20 as ForceTrainer",
            AC::CHARACTER,
            ADiff::NORMAL,
            20) },

    { AT::BLUE_MAGE_TITLE_L20,
        std::make_shared<AD>(
            AT::BLUE_MAGE_TITLE_L20,
            "呪術師",
            "Spellbinder",
            "青魔道師としてレベル20に到達した",
            "Reached level 20 as Blue-Mage",
            AC::CHARACTER,
            ADiff::NORMAL,
            20) },

    { AT::CAVALRY_TITLE_L20,
        std::make_shared<AD>(
            AT::CAVALRY_TITLE_L20,
            "古参兵",
            "Veteran",
            "騎兵としてレベル20に到達した",
            "Reached level 20 as Cavalry",
            AC::CHARACTER,
            ADiff::NORMAL,
            20) },

    { AT::BERSERKER_TITLE_L20,
        std::make_shared<AD>(
            AT::BERSERKER_TITLE_L20,
            "怒りの公爵",
            "Rage Prince",
            "狂戦士としてレベル20に到達した",
            "Reached level 20 as Berserker",
            AC::CHARACTER,
            ADiff::NORMAL,
            20) },

    { AT::SMITH_TITLE_L20,
        std::make_shared<AD>(
            AT::SMITH_TITLE_L20,
            "銀を鍛えし者",
            "Silver smith",
            "鍛冶師としてレベル20に到達した",
            "Reached level 20 as Weaponsmith",
            AC::CHARACTER,
            ADiff::NORMAL,
            20) },

    { AT::MIRROR_MASTER_TITLE_L20,
        std::make_shared<AD>(
            AT::MIRROR_MASTER_TITLE_L20,
            "鏡術師",
            "Mirrormagician",
            "鏡使いとしてレベル20に到達した",
            "Reached level 20 as Mirror-Master",
            AC::CHARACTER,
            ADiff::NORMAL,
            20) },

    { AT::NINJA_TITLE_L20,
        std::make_shared<AD>(
            AT::NINJA_TITLE_L20,
            "短刀使い",
            "Knifer",
            "忍者としてレベル20に到達した",
            "Reached level 20 as Ninja",
            AC::CHARACTER,
            ADiff::NORMAL,
            20) },

    { AT::SNIPER_TITLE_L20,
        std::make_shared<AD>(
            AT::SNIPER_TITLE_L20,
            "古参兵",
            "Veteran",
            "スナイパーとしてレベル20に到達した",
            "Reached level 20 as Sniper",
            AC::CHARACTER,
            ADiff::NORMAL,
            20) },

    { AT::ELEMENTALIST_TITLE_L20,
        std::make_shared<AD>(
            AT::ELEMENTALIST_TITLE_L20,
            "呪術師",
            "Spellbinder",
            "元素使いとしてレベル20に到達した",
            "Reached level 20 as Elementalist",
            AC::CHARACTER,
            ADiff::NORMAL,
            20) },

    // レベル25（称号6段階目）
    { AT::WARRIOR_TITLE_L25,
        std::make_shared<AD>(
            AT::WARRIOR_TITLE_L25,
            "剣士",
            "Swordsman",
            "戦士としてレベル25に到達した",
            "Reached level 25 as Warrior",
            AC::CHARACTER,
            ADiff::NORMAL,
            25) },

    { AT::MAGE_TITLE_L25,
        std::make_shared<AD>(
            AT::MAGE_TITLE_L25,
            "召霊師",
            "Evoker",
            "メイジとしてレベル25に到達した",
            "Reached level 25 as Mage",
            AC::CHARACTER,
            ADiff::NORMAL,
            25) },

    { AT::PRIEST_TITLE_L25,
        std::make_shared<AD>(
            AT::PRIEST_TITLE_L25,
            "伝道師",
            "Canon",
            "プリーストとしてレベル25に到達した",
            "Reached level 25 as Priest",
            AC::CHARACTER,
            ADiff::NORMAL,
            25) },

    { AT::ROGUE_TITLE_L25,
        std::make_shared<AD>(
            AT::ROGUE_TITLE_L25,
            "ペテン師",
            "Sharper",
            "盗賊としてレベル25に到達した",
            "Reached level 25 as Rogue",
            AC::CHARACTER,
            ADiff::NORMAL,
            25) },

    { AT::RANGER_TITLE_L25,
        std::make_shared<AD>(
            AT::RANGER_TITLE_L25,
            "追跡者",
            "Tracker",
            "レンジャーとしてレベル25に到達した",
            "Reached level 25 as Ranger",
            AC::CHARACTER,
            ADiff::NORMAL,
            25) },

    { AT::PALADIN_TITLE_L25,
        std::make_shared<AD>(
            AT::PALADIN_TITLE_L25,
            "護衛者",
            "Warder",
            "パラディンとしてレベル25に到達した",
            "Reached level 25 as Paladin",
            AC::CHARACTER,
            ADiff::NORMAL,
            25) },

    { AT::WARRIOR_MAGE_TITLE_L25,
        std::make_shared<AD>(
            AT::WARRIOR_MAGE_TITLE_L25,
            "魔術兵士",
            "Enchanter",
            "魔法戦士としてレベル25に到達した",
            "Reached level 25 as Warrior-Mage",
            AC::CHARACTER,
            ADiff::NORMAL,
            25) },

    { AT::CHAOS_WARRIOR_TITLE_L25,
        std::make_shared<AD>(
            AT::CHAOS_WARRIOR_TITLE_L25,
            "剣士",
            "Swordsman",
            "混沌の戦士としてレベル25に到達した",
            "Reached level 25 as Chaos-Warrior",
            AC::CHARACTER,
            ADiff::NORMAL,
            25) },

    { AT::MONK_TITLE_L25,
        std::make_shared<AD>(
            AT::MONK_TITLE_L25,
            "師範",
            "Master",
            "修行僧としてレベル25に到達した",
            "Reached level 25 as Monk",
            AC::CHARACTER,
            ADiff::NORMAL,
            25) },

    { AT::MINDCRAFTER_TITLE_L25,
        std::make_shared<AD>(
            AT::MINDCRAFTER_TITLE_L25,
            "黙想士",
            "Contemplator",
            "超能力者としてレベル25に到達した",
            "Reached level 25 as Mindcrafter",
            AC::CHARACTER,
            ADiff::NORMAL,
            25) },

    { AT::HIGH_MAGE_TITLE_L25,
        std::make_shared<AD>(
            AT::HIGH_MAGE_TITLE_L25,
            "召霊師",
            "Evoker",
            "ハイ=メイジとしてレベル25に到達した",
            "Reached level 25 as High-Mage",
            AC::CHARACTER,
            ADiff::NORMAL,
            25) },

    { AT::TOURIST_TITLE_L25,
        std::make_shared<AD>(
            AT::TOURIST_TITLE_L25,
            "旅行者",
            "Traveler",
            "観光客としてレベル25に到達した",
            "Reached level 25 as Tourist",
            AC::CHARACTER,
            ADiff::NORMAL,
            25) },

    { AT::IMITATOR_TITLE_L25,
        std::make_shared<AD>(
            AT::IMITATOR_TITLE_L25,
            "そこそこ",
            "All right",
            "ものまね師としてレベル25に到達した",
            "Reached level 25 as Imitator",
            AC::CHARACTER,
            ADiff::NORMAL,
            25) },

    { AT::BEASTMASTER_TITLE_L25,
        std::make_shared<AD>(
            AT::BEASTMASTER_TITLE_L25,
            "トラ使い",
            "Tiger Master",
            "魔獣使いとしてレベル25に到達した",
            "Reached level 25 as BeastMaster",
            AC::CHARACTER,
            ADiff::NORMAL,
            25) },

    { AT::SORCERER_TITLE_L25,
        std::make_shared<AD>(
            AT::SORCERER_TITLE_L25,
            "召霊師",
            "Evoker",
            "スペルマスターとしてレベル25に到達した",
            "Reached level 25 as Sorcerer",
            AC::CHARACTER,
            ADiff::NORMAL,
            25) },

    { AT::ARCHER_TITLE_L25,
        std::make_shared<AD>(
            AT::ARCHER_TITLE_L25,
            "弩弓士",
            "Bowman",
            "アーチャーとしてレベル25に到達した",
            "Reached level 25 as Archer",
            AC::CHARACTER,
            ADiff::NORMAL,
            25) },

    { AT::MAGIC_EATER_TITLE_L25,
        std::make_shared<AD>(
            AT::MAGIC_EATER_TITLE_L25,
            "秘術師",
            "Conjurer",
            "魔道具術師としてレベル25に到達した",
            "Reached level 25 as Magic-Eater",
            AC::CHARACTER,
            ADiff::NORMAL,
            25) },

    { AT::BARD_TITLE_L25,
        std::make_shared<AD>(
            AT::BARD_TITLE_L25,
            "心の癒し手",
            "Minstrel",
            "吟遊詩人としてレベル25に到達した",
            "Reached level 25 as Bard",
            AC::CHARACTER,
            ADiff::NORMAL,
            25) },

    { AT::RED_MAGE_TITLE_L25,
        std::make_shared<AD>(
            AT::RED_MAGE_TITLE_L25,
            "魔術兵士",
            "Enchanter",
            "赤魔道師としてレベル25に到達した",
            "Reached level 25 as Red-Mage",
            AC::CHARACTER,
            ADiff::NORMAL,
            25) },

    { AT::SAMURAI_TITLE_L25,
        std::make_shared<AD>(
            AT::SAMURAI_TITLE_L25,
            "師範",
            "Master",
            "剣術家としてレベル25に到達した",
            "Reached level 25 as Samurai",
            AC::CHARACTER,
            ADiff::NORMAL,
            25) },

    { AT::FORCETRAINER_TITLE_L25,
        std::make_shared<AD>(
            AT::FORCETRAINER_TITLE_L25,
            "師範",
            "Master",
            "練気術師としてレベル25に到達した",
            "Reached level 25 as ForceTrainer",
            AC::CHARACTER,
            ADiff::NORMAL,
            25) },

    { AT::BLUE_MAGE_TITLE_L25,
        std::make_shared<AD>(
            AT::BLUE_MAGE_TITLE_L25,
            "召霊師",
            "Evoker",
            "青魔道師としてレベル25に到達した",
            "Reached level 25 as Blue-Mage",
            AC::CHARACTER,
            ADiff::NORMAL,
            25) },

    { AT::CAVALRY_TITLE_L25,
        std::make_shared<AD>(
            AT::CAVALRY_TITLE_L25,
            "剣士",
            "Swordsman",
            "騎兵としてレベル25に到達した",
            "Reached level 25 as Cavalry",
            AC::CHARACTER,
            ADiff::NORMAL,
            25) },

    { AT::BERSERKER_TITLE_L25,
        std::make_shared<AD>(
            AT::BERSERKER_TITLE_L25,
            "怒りの公爵",
            "Rage Prince",
            "狂戦士としてレベル25に到達した",
            "Reached level 25 as Berserker",
            AC::CHARACTER,
            ADiff::NORMAL,
            25) },

    { AT::SMITH_TITLE_L25,
        std::make_shared<AD>(
            AT::SMITH_TITLE_L25,
            "竜を鍛えし者",
            "Dragon smith",
            "鍛冶師としてレベル25に到達した",
            "Reached level 25 as Weaponsmith",
            AC::CHARACTER,
            ADiff::NORMAL,
            25) },

    { AT::MIRROR_MASTER_TITLE_L25,
        std::make_shared<AD>(
            AT::MIRROR_MASTER_TITLE_L25,
            "鏡導師",
            "Mirror Guru",
            "鏡使いとしてレベル25に到達した",
            "Reached level 25 as Mirror-Master",
            AC::CHARACTER,
            ADiff::NORMAL,
            25) },

    { AT::NINJA_TITLE_L25,
        std::make_shared<AD>(
            AT::NINJA_TITLE_L25,
            "切り裂き",
            "Bladesman",
            "忍者としてレベル25に到達した",
            "Reached level 25 as Ninja",
            AC::CHARACTER,
            ADiff::NORMAL,
            25) },

    { AT::SNIPER_TITLE_L25,
        std::make_shared<AD>(
            AT::SNIPER_TITLE_L25,
            "剣士",
            "Swordsman",
            "スナイパーとしてレベル25に到達した",
            "Reached level 25 as Sniper",
            AC::CHARACTER,
            ADiff::NORMAL,
            25) },

    { AT::ELEMENTALIST_TITLE_L25,
        std::make_shared<AD>(
            AT::ELEMENTALIST_TITLE_L25,
            "召霊師",
            "Evoker",
            "元素使いとしてレベル25に到達した",
            "Reached level 25 as Elementalist",
            AC::CHARACTER,
            ADiff::NORMAL,
            25) },

    // レベル30（称号7段階目）
    { AT::WARRIOR_TITLE_L30,
        std::make_shared<AD>(
            AT::WARRIOR_TITLE_L30,
            "闘士",
            "Champion",
            "戦士としてレベル30に到達した",
            "Reached level 30 as Warrior",
            AC::CHARACTER,
            ADiff::NORMAL,
            30) },

    { AT::MAGE_TITLE_L30,
        std::make_shared<AD>(
            AT::MAGE_TITLE_L30,
            "召魔師",
            "Conjurer",
            "メイジとしてレベル30に到達した",
            "Reached level 30 as Mage",
            AC::CHARACTER,
            ADiff::NORMAL,
            30) },

    { AT::PRIEST_TITLE_L30,
        std::make_shared<AD>(
            AT::PRIEST_TITLE_L30,
            "牧師",
            "Priest",
            "プリーストとしてレベル30に到達した",
            "Reached level 30 as Priest",
            AC::CHARACTER,
            ADiff::NORMAL,
            30) },

    { AT::ROGUE_TITLE_L30,
        std::make_shared<AD>(
            AT::ROGUE_TITLE_L30,
            "ロウシーフ",
            "Low Thief",
            "盗賊としてレベル30に到達した",
            "Reached level 30 as Rogue",
            AC::CHARACTER,
            ADiff::NORMAL,
            30) },

    { AT::RANGER_TITLE_L30,
        std::make_shared<AD>(
            AT::RANGER_TITLE_L30,
            "先導者",
            "Guide",
            "レンジャーとしてレベル30に到達した",
            "Reached level 30 as Ranger",
            AC::CHARACTER,
            ADiff::NORMAL,
            30) },

    { AT::PALADIN_TITLE_L30,
        std::make_shared<AD>(
            AT::PALADIN_TITLE_L30,
            "騎士",
            "Knight",
            "パラディンとしてレベル30に到達した",
            "Reached level 30 as Paladin",
            AC::CHARACTER,
            ADiff::NORMAL,
            30) },

    { AT::WARRIOR_MAGE_TITLE_L30,
        std::make_shared<AD>(
            AT::WARRIOR_MAGE_TITLE_L30,
            "魔術闘士",
            "Champion",
            "魔法戦士としてレベル30に到達した",
            "Reached level 30 as Warrior-Mage",
            AC::CHARACTER,
            ADiff::NORMAL,
            30) },

    { AT::CHAOS_WARRIOR_TITLE_L30,
        std::make_shared<AD>(
            AT::CHAOS_WARRIOR_TITLE_L30,
            "闘士",
            "Champion",
            "混沌の戦士としてレベル30に到達した",
            "Reached level 30 as Chaos-Warrior",
            AC::CHARACTER,
            ADiff::NORMAL,
            30) },

    { AT::MONK_TITLE_L30,
        std::make_shared<AD>(
            AT::MONK_TITLE_L30,
            "道場主",
            "Soft Master",
            "修行僧としてレベル30に到達した",
            "Reached level 30 as Monk",
            AC::CHARACTER,
            ADiff::NORMAL,
            30) },

    { AT::MINDCRAFTER_TITLE_L30,
        std::make_shared<AD>(
            AT::MINDCRAFTER_TITLE_L30,
            "心術士",
            "Mentalist",
            "超能力者としてレベル30に到達した",
            "Reached level 30 as Mindcrafter",
            AC::CHARACTER,
            ADiff::NORMAL,
            30) },

    { AT::HIGH_MAGE_TITLE_L30,
        std::make_shared<AD>(
            AT::HIGH_MAGE_TITLE_L30,
            "召魔師",
            "Conjurer",
            "ハイ=メイジとしてレベル30に到達した",
            "Reached level 30 as High-Mage",
            AC::CHARACTER,
            ADiff::NORMAL,
            30) },

    { AT::TOURIST_TITLE_L30,
        std::make_shared<AD>(
            AT::TOURIST_TITLE_L30,
            "放浪者",
            "Journeyer",
            "観光客としてレベル30に到達した",
            "Reached level 30 as Tourist",
            AC::CHARACTER,
            ADiff::NORMAL,
            30) },

    { AT::IMITATOR_TITLE_L30,
        std::make_shared<AD>(
            AT::IMITATOR_TITLE_L30,
            "まあまあ",
            "Not bad",
            "ものまね師としてレベル30に到達した",
            "Reached level 30 as Imitator",
            AC::CHARACTER,
            ADiff::NORMAL,
            30) },

    { AT::BEASTMASTER_TITLE_L30,
        std::make_shared<AD>(
            AT::BEASTMASTER_TITLE_L30,
            "甲虫使い",
            "Beetle Master",
            "魔獣使いとしてレベル30に到達した",
            "Reached level 30 as BeastMaster",
            AC::CHARACTER,
            ADiff::NORMAL,
            30) },

    { AT::SORCERER_TITLE_L30,
        std::make_shared<AD>(
            AT::SORCERER_TITLE_L30,
            "召魔師",
            "Conjurer",
            "スペルマスターとしてレベル30に到達した",
            "Reached level 30 as Sorcerer",
            AC::CHARACTER,
            ADiff::NORMAL,
            30) },

    { AT::ARCHER_TITLE_L30,
        std::make_shared<AD>(
            AT::ARCHER_TITLE_L30,
            "闘士",
            "Champion",
            "アーチャーとしてレベル30に到達した",
            "Reached level 30 as Archer",
            AC::CHARACTER,
            ADiff::NORMAL,
            30) },

    { AT::MAGIC_EATER_TITLE_L30,
        std::make_shared<AD>(
            AT::MAGIC_EATER_TITLE_L30,
            "熟練者",
            "Magician",
            "魔道具術師としてレベル30に到達した",
            "Reached level 30 as Magic-Eater",
            AC::CHARACTER,
            ADiff::NORMAL,
            30) },

    { AT::BARD_TITLE_L30,
        std::make_shared<AD>(
            AT::BARD_TITLE_L30,
            "竪琴師",
            "Harper",
            "吟遊詩人としてレベル30に到達した",
            "Reached level 30 as Bard",
            AC::CHARACTER,
            ADiff::NORMAL,
            30) },

    { AT::RED_MAGE_TITLE_L30,
        std::make_shared<AD>(
            AT::RED_MAGE_TITLE_L30,
            "魔術闘士",
            "Champion",
            "赤魔道師としてレベル30に到達した",
            "Reached level 30 as Red-Mage",
            AC::CHARACTER,
            ADiff::NORMAL,
            30) },

    { AT::SAMURAI_TITLE_L30,
        std::make_shared<AD>(
            AT::SAMURAI_TITLE_L30,
            "道場主",
            "Soft Master",
            "剣術家としてレベル30に到達した",
            "Reached level 30 as Samurai",
            AC::CHARACTER,
            ADiff::NORMAL,
            30) },

    { AT::FORCETRAINER_TITLE_L30,
        std::make_shared<AD>(
            AT::FORCETRAINER_TITLE_L30,
            "道場主",
            "Soft Master",
            "練気術師としてレベル30に到達した",
            "Reached level 30 as ForceTrainer",
            AC::CHARACTER,
            ADiff::NORMAL,
            30) },

    { AT::BLUE_MAGE_TITLE_L30,
        std::make_shared<AD>(
            AT::BLUE_MAGE_TITLE_L30,
            "召魔師",
            "Conjurer",
            "青魔道師としてレベル30に到達した",
            "Reached level 30 as Blue-Mage",
            AC::CHARACTER,
            ADiff::NORMAL,
            30) },

    { AT::CAVALRY_TITLE_L30,
        std::make_shared<AD>(
            AT::CAVALRY_TITLE_L30,
            "闘士",
            "Champion",
            "騎兵としてレベル30に到達した",
            "Reached level 30 as Cavalry",
            AC::CHARACTER,
            ADiff::NORMAL,
            30) },

    { AT::BERSERKER_TITLE_L30,
        std::make_shared<AD>(
            AT::BERSERKER_TITLE_L30,
            "怒りの公爵",
            "Rage Prince",
            "狂戦士としてレベル30に到達した",
            "Reached level 30 as Berserker",
            AC::CHARACTER,
            ADiff::NORMAL,
            30) },

    { AT::SMITH_TITLE_L30,
        std::make_shared<AD>(
            AT::SMITH_TITLE_L30,
            "霊を鍛えし者",
            "Spirit smith",
            "鍛冶師としてレベル30に到達した",
            "Reached level 30 as Weaponsmith",
            AC::CHARACTER,
            ADiff::NORMAL,
            30) },

    { AT::MIRROR_MASTER_TITLE_L30,
        std::make_shared<AD>(
            AT::MIRROR_MASTER_TITLE_L30,
            "鏡の賢者",
            "Mirror Mage",
            "鏡使いとしてレベル30に到達した",
            "Reached level 30 as Mirror-Master",
            AC::CHARACTER,
            ADiff::NORMAL,
            30) },

    { AT::NINJA_TITLE_L30,
        std::make_shared<AD>(
            AT::NINJA_TITLE_L30,
            "凄腕",
            "Hashishin",
            "忍者としてレベル30に到達した",
            "Reached level 30 as Ninja",
            AC::CHARACTER,
            ADiff::NORMAL,
            30) },

    { AT::SNIPER_TITLE_L30,
        std::make_shared<AD>(
            AT::SNIPER_TITLE_L30,
            "闘士",
            "Champion",
            "スナイパーとしてレベル30に到達した",
            "Reached level 30 as Sniper",
            AC::CHARACTER,
            ADiff::NORMAL,
            30) },

    { AT::ELEMENTALIST_TITLE_L30,
        std::make_shared<AD>(
            AT::ELEMENTALIST_TITLE_L30,
            "召魔師",
            "Conjurer",
            "元素使いとしてレベル30に到達した",
            "Reached level 30 as Elementalist",
            AC::CHARACTER,
            ADiff::NORMAL,
            30) },

    // レベル35（称号8段階目）
    { AT::WARRIOR_TITLE_L35,
        std::make_shared<AD>(
            AT::WARRIOR_TITLE_L35,
            "英雄",
            "Hero",
            "戦士としてレベル35に到達した",
            "Reached level 35 as Warrior",
            AC::CHARACTER,
            ADiff::HARD,
            35) },

    { AT::MAGE_TITLE_L35,
        std::make_shared<AD>(
            AT::MAGE_TITLE_L35,
            "魔術師",
            "Warlock",
            "メイジとしてレベル35に到達した",
            "Reached level 35 as Mage",
            AC::CHARACTER,
            ADiff::HARD,
            35) },

    { AT::PRIEST_TITLE_L35,
        std::make_shared<AD>(
            AT::PRIEST_TITLE_L35,
            "聖人",
            "High Priest",
            "プリーストとしてレベル35に到達した",
            "Reached level 35 as Priest",
            AC::CHARACTER,
            ADiff::HARD,
            35) },

    { AT::ROGUE_TITLE_L35,
        std::make_shared<AD>(
            AT::ROGUE_TITLE_L35,
            "ハイシーフ",
            "High Thief",
            "盗賊としてレベル35に到達した",
            "Reached level 35 as Rogue",
            AC::CHARACTER,
            ADiff::HARD,
            35) },

    { AT::RANGER_TITLE_L35,
        std::make_shared<AD>(
            AT::RANGER_TITLE_L35,
            "探険者",
            "Pathfinder",
            "レンジャーとしてレベル35に到達した",
            "Reached level 35 as Ranger",
            AC::CHARACTER,
            ADiff::HARD,
            35) },

    { AT::PALADIN_TITLE_L35,
        std::make_shared<AD>(
            AT::PALADIN_TITLE_L35,
            "重騎士",
            "Guardian",
            "パラディンとしてレベル35に到達した",
            "Reached level 35 as Paladin",
            AC::CHARACTER,
            ADiff::HARD,
            35) },

    { AT::WARRIOR_MAGE_TITLE_L35,
        std::make_shared<AD>(
            AT::WARRIOR_MAGE_TITLE_L35,
            "魔術の英雄",
            "Mage-Hero",
            "魔法戦士としてレベル35に到達した",
            "Reached level 35 as Warrior-Mage",
            AC::CHARACTER,
            ADiff::HARD,
            35) },

    { AT::CHAOS_WARRIOR_TITLE_L35,
        std::make_shared<AD>(
            AT::CHAOS_WARRIOR_TITLE_L35,
            "混沌の英雄",
            "Chaos Hero",
            "混沌の戦士としてレベル35に到達した",
            "Reached level 35 as Chaos-Warrior",
            AC::CHARACTER,
            ADiff::HARD,
            35) },

    { AT::MONK_TITLE_L35,
        std::make_shared<AD>(
            AT::MONK_TITLE_L35,
            "名人",
            "Hard Master",
            "修行僧としてレベル35に到達した",
            "Reached level 35 as Monk",
            AC::CHARACTER,
            ADiff::HARD,
            35) },

    { AT::MINDCRAFTER_TITLE_L35,
        std::make_shared<AD>(
            AT::MINDCRAFTER_TITLE_L35,
            "サイキック",
            "Psychic",
            "超能力者としてレベル35に到達した",
            "Reached level 35 as Mindcrafter",
            AC::CHARACTER,
            ADiff::HARD,
            35) },

    { AT::HIGH_MAGE_TITLE_L35,
        std::make_shared<AD>(
            AT::HIGH_MAGE_TITLE_L35,
            "魔術師",
            "Warlock",
            "ハイ=メイジとしてレベル35に到達した",
            "Reached level 35 as High-Mage",
            AC::CHARACTER,
            ADiff::HARD,
            35) },

    { AT::TOURIST_TITLE_L35,
        std::make_shared<AD>(
            AT::TOURIST_TITLE_L35,
            "航海者",
            "Voyager",
            "観光客としてレベル35に到達した",
            "Reached level 35 as Tourist",
            AC::CHARACTER,
            ADiff::HARD,
            35) },

    { AT::IMITATOR_TITLE_L35,
        std::make_shared<AD>(
            AT::IMITATOR_TITLE_L35,
            "なかなか",
            "Considerable",
            "ものまね師としてレベル35に到達した",
            "Reached level 35 as Imitator",
            AC::CHARACTER,
            ADiff::HARD,
            35) },

    { AT::BEASTMASTER_TITLE_L35,
        std::make_shared<AD>(
            AT::BEASTMASTER_TITLE_L35,
            "ヒドラ使い",
            "Hydra Master",
            "魔獣使いとしてレベル35に到達した",
            "Reached level 35 as BeastMaster",
            AC::CHARACTER,
            ADiff::HARD,
            35) },

    { AT::SORCERER_TITLE_L35,
        std::make_shared<AD>(
            AT::SORCERER_TITLE_L35,
            "魔術師",
            "Warlock",
            "スペルマスターとしてレベル35に到達した",
            "Reached level 35 as Sorcerer",
            AC::CHARACTER,
            ADiff::HARD,
            35) },

    { AT::ARCHER_TITLE_L35,
        std::make_shared<AD>(
            AT::ARCHER_TITLE_L35,
            "英雄",
            "Hero",
            "アーチャーとしてレベル35に到達した",
            "Reached level 35 as Archer",
            AC::CHARACTER,
            ADiff::HARD,
            35) },

    { AT::MAGIC_EATER_TITLE_L35,
        std::make_shared<AD>(
            AT::MAGIC_EATER_TITLE_L35,
            "達人",
            "Master",
            "魔道具術師としてレベル35に到達した",
            "Reached level 35 as Magic-Eater",
            AC::CHARACTER,
            ADiff::HARD,
            35) },

    { AT::BARD_TITLE_L35,
        std::make_shared<AD>(
            AT::BARD_TITLE_L35,
            "伝承の紡ぎ手",
            "Loreweaver",
            "吟遊詩人としてレベル35に到達した",
            "Reached level 35 as Bard",
            AC::CHARACTER,
            ADiff::HARD,
            35) },

    { AT::RED_MAGE_TITLE_L35,
        std::make_shared<AD>(
            AT::RED_MAGE_TITLE_L35,
            "魔術の英雄",
            "Mage-Hero",
            "赤魔道師としてレベル35に到達した",
            "Reached level 35 as Red-Mage",
            AC::CHARACTER,
            ADiff::HARD,
            35) },

    { AT::SAMURAI_TITLE_L35,
        std::make_shared<AD>(
            AT::SAMURAI_TITLE_L35,
            "名人",
            "Hard Master",
            "剣術家としてレベル35に到達した",
            "Reached level 35 as Samurai",
            AC::CHARACTER,
            ADiff::HARD,
            35) },

    { AT::FORCETRAINER_TITLE_L35,
        std::make_shared<AD>(
            AT::FORCETRAINER_TITLE_L35,
            "名人",
            "Hard Master",
            "練気術師としてレベル35に到達した",
            "Reached level 35 as ForceTrainer",
            AC::CHARACTER,
            ADiff::HARD,
            35) },

    { AT::BLUE_MAGE_TITLE_L35,
        std::make_shared<AD>(
            AT::BLUE_MAGE_TITLE_L35,
            "魔術師",
            "Warlock",
            "青魔道師としてレベル35に到達した",
            "Reached level 35 as Blue-Mage",
            AC::CHARACTER,
            ADiff::HARD,
            35) },

    { AT::CAVALRY_TITLE_L35,
        std::make_shared<AD>(
            AT::CAVALRY_TITLE_L35,
            "英雄",
            "Hero",
            "騎兵としてレベル35に到達した",
            "Reached level 35 as Cavalry",
            AC::CHARACTER,
            ADiff::HARD,
            35) },

    { AT::BERSERKER_TITLE_L35,
        std::make_shared<AD>(
            AT::BERSERKER_TITLE_L35,
            "怒りの王",
            "Rage King",
            "狂戦士としてレベル35に到達した",
            "Reached level 35 as Berserker",
            AC::CHARACTER,
            ADiff::HARD,
            35) },

    { AT::SMITH_TITLE_L35,
        std::make_shared<AD>(
            AT::SMITH_TITLE_L35,
            "魔を鍛えし者",
            "Magic smith",
            "鍛冶師としてレベル35に到達した",
            "Reached level 35 as Weaponsmith",
            AC::CHARACTER,
            ADiff::HARD,
            35) },

    { AT::MIRROR_MASTER_TITLE_L35,
        std::make_shared<AD>(
            AT::MIRROR_MASTER_TITLE_L35,
            "鏡の王",
            "Mirror King",
            "鏡使いとしてレベル35に到達した",
            "Reached level 35 as Mirror-Master",
            AC::CHARACTER,
            ADiff::HARD,
            35) },

    { AT::NINJA_TITLE_L35,
        std::make_shared<AD>(
            AT::NINJA_TITLE_L35,
            "漆黒の刃",
            "Black Dagger",
            "忍者としてレベル35に到達した",
            "Reached level 35 as Ninja",
            AC::CHARACTER,
            ADiff::HARD,
            35) },

    { AT::SNIPER_TITLE_L35,
        std::make_shared<AD>(
            AT::SNIPER_TITLE_L35,
            "英雄",
            "Hero",
            "スナイパーとしてレベル35に到達した",
            "Reached level 35 as Sniper",
            AC::CHARACTER,
            ADiff::HARD,
            35) },

    { AT::ELEMENTALIST_TITLE_L35,
        std::make_shared<AD>(
            AT::ELEMENTALIST_TITLE_L35,
            "魔術師",
            "Warlock",
            "元素使いとしてレベル35に到達した",
            "Reached level 35 as Elementalist",
            AC::CHARACTER,
            ADiff::HARD,
            35) },

    // レベル40（称号9段階目）
    { AT::WARRIOR_TITLE_L40,
        std::make_shared<AD>(
            AT::WARRIOR_TITLE_L40,
            "男爵",
            "Baron",
            "戦士としてレベル40に到達した",
            "Reached level 40 as Warrior",
            AC::CHARACTER,
            ADiff::HARD,
            40) },

    { AT::MAGE_TITLE_L40,
        std::make_shared<AD>(
            AT::MAGE_TITLE_L40,
            "魔道師",
            "Sorcerer",
            "メイジとしてレベル40に到達した",
            "Reached level 40 as Mage",
            AC::CHARACTER,
            ADiff::HARD,
            40) },

    { AT::PRIEST_TITLE_L40,
        std::make_shared<AD>(
            AT::PRIEST_TITLE_L40,
            "祭司",
            "Cardinal",
            "プリーストとしてレベル40に到達した",
            "Reached level 40 as Priest",
            AC::CHARACTER,
            ADiff::HARD,
            40) },

    { AT::ROGUE_TITLE_L40,
        std::make_shared<AD>(
            AT::ROGUE_TITLE_L40,
            "マスター",
            "Master Thief",
            "盗賊としてレベル40に到達した",
            "Reached level 40 as Rogue",
            AC::CHARACTER,
            ADiff::HARD,
            40) },

    { AT::RANGER_TITLE_L40,
        std::make_shared<AD>(
            AT::RANGER_TITLE_L40,
            "野伏",
            "Low Ranger",
            "レンジャーとしてレベル40に到達した",
            "Reached level 40 as Ranger",
            AC::CHARACTER,
            ADiff::HARD,
            40) },

    { AT::PALADIN_TITLE_L40,
        std::make_shared<AD>(
            AT::PALADIN_TITLE_L40,
            "聖騎士",
            "Low Paladin",
            "パラディンとしてレベル40に到達した",
            "Reached level 40 as Paladin",
            AC::CHARACTER,
            ADiff::HARD,
            40) },

    { AT::WARRIOR_MAGE_TITLE_L40,
        std::make_shared<AD>(
            AT::WARRIOR_MAGE_TITLE_L40,
            "魔男爵",
            "Baron Mage",
            "魔法戦士としてレベル40に到達した",
            "Reached level 40 as Warrior-Mage",
            AC::CHARACTER,
            ADiff::HARD,
            40) },

    { AT::CHAOS_WARRIOR_TITLE_L40,
        std::make_shared<AD>(
            AT::CHAOS_WARRIOR_TITLE_L40,
            "混沌の男爵",
            "Chaos Baron",
            "混沌の戦士としてレベル40に到達した",
            "Reached level 40 as Chaos-Warrior",
            AC::CHARACTER,
            ADiff::HARD,
            40) },

    { AT::MONK_TITLE_L40,
        std::make_shared<AD>(
            AT::MONK_TITLE_L40,
            "大名人",
            "Flower Master",
            "修行僧としてレベル40に到達した",
            "Reached level 40 as Monk",
            AC::CHARACTER,
            ADiff::HARD,
            40) },

    { AT::MINDCRAFTER_TITLE_L40,
        std::make_shared<AD>(
            AT::MINDCRAFTER_TITLE_L40,
            "サイオニック",
            "Psionicist",
            "超能力者としてレベル40に到達した",
            "Reached level 40 as Mindcrafter",
            AC::CHARACTER,
            ADiff::HARD,
            40) },

    { AT::HIGH_MAGE_TITLE_L40,
        std::make_shared<AD>(
            AT::HIGH_MAGE_TITLE_L40,
            "魔道師",
            "Sorcerer",
            "ハイ=メイジとしてレベル40に到達した",
            "Reached level 40 as High-Mage",
            AC::CHARACTER,
            ADiff::HARD,
            40) },

    { AT::TOURIST_TITLE_L40,
        std::make_shared<AD>(
            AT::TOURIST_TITLE_L40,
            "探検家",
            "Explorer",
            "観光客としてレベル40に到達した",
            "Reached level 40 as Tourist",
            AC::CHARACTER,
            ADiff::HARD,
            40) },

    { AT::IMITATOR_TITLE_L40,
        std::make_shared<AD>(
            AT::IMITATOR_TITLE_L40,
            "いけいけ",
            "Go go",
            "ものまね師としてレベル40に到達した",
            "Reached level 40 as Imitator",
            AC::CHARACTER,
            ADiff::HARD,
            40) },

    { AT::BEASTMASTER_TITLE_L40,
        std::make_shared<AD>(
            AT::BEASTMASTER_TITLE_L40,
            "ハウンド使い",
            "Hound Master",
            "魔獣使いとしてレベル40に到達した",
            "Reached level 40 as BeastMaster",
            AC::CHARACTER,
            ADiff::HARD,
            40) },

    { AT::SORCERER_TITLE_L40,
        std::make_shared<AD>(
            AT::SORCERER_TITLE_L40,
            "魔道師",
            "Sorcerer",
            "スペルマスターとしてレベル40に到達した",
            "Reached level 40 as Sorcerer",
            AC::CHARACTER,
            ADiff::HARD,
            40) },

    { AT::ARCHER_TITLE_L40,
        std::make_shared<AD>(
            AT::ARCHER_TITLE_L40,
            "男爵",
            "Baron",
            "アーチャーとしてレベル40に到達した",
            "Reached level 40 as Archer",
            AC::CHARACTER,
            ADiff::HARD,
            40) },

    { AT::MAGIC_EATER_TITLE_L40,
        std::make_shared<AD>(
            AT::MAGIC_EATER_TITLE_L40,
            "達人",
            "Master",
            "魔道具術師としてレベル40に到達した",
            "Reached level 40 as Magic-Eater",
            AC::CHARACTER,
            ADiff::HARD,
            40) },

    { AT::BARD_TITLE_L40,
        std::make_shared<AD>(
            AT::BARD_TITLE_L40,
            "詩神の申し子",
            "Muse",
            "吟遊詩人としてレベル40に到達した",
            "Reached level 40 as Bard",
            AC::CHARACTER,
            ADiff::HARD,
            40) },

    { AT::RED_MAGE_TITLE_L40,
        std::make_shared<AD>(
            AT::RED_MAGE_TITLE_L40,
            "魔男爵",
            "Baron Mage",
            "赤魔道師としてレベル40に到達した",
            "Reached level 40 as Red-Mage",
            AC::CHARACTER,
            ADiff::HARD,
            40) },

    { AT::SAMURAI_TITLE_L40,
        std::make_shared<AD>(
            AT::SAMURAI_TITLE_L40,
            "大名人",
            "Flower Master",
            "剣術家としてレベル40に到達した",
            "Reached level 40 as Samurai",
            AC::CHARACTER,
            ADiff::HARD,
            40) },

    { AT::FORCETRAINER_TITLE_L40,
        std::make_shared<AD>(
            AT::FORCETRAINER_TITLE_L40,
            "大名人",
            "Flower Master",
            "練気術師としてレベル40に到達した",
            "Reached level 40 as ForceTrainer",
            AC::CHARACTER,
            ADiff::HARD,
            40) },

    { AT::BLUE_MAGE_TITLE_L40,
        std::make_shared<AD>(
            AT::BLUE_MAGE_TITLE_L40,
            "魔道師",
            "Sorcerer",
            "青魔道師としてレベル40に到達した",
            "Reached level 40 as Blue-Mage",
            AC::CHARACTER,
            ADiff::HARD,
            40) },

    { AT::CAVALRY_TITLE_L40,
        std::make_shared<AD>(
            AT::CAVALRY_TITLE_L40,
            "男爵",
            "Baron",
            "騎兵としてレベル40に到達した",
            "Reached level 40 as Cavalry",
            AC::CHARACTER,
            ADiff::HARD,
            40) },

    { AT::BERSERKER_TITLE_L40,
        std::make_shared<AD>(
            AT::BERSERKER_TITLE_L40,
            "怒りの王",
            "Rage King",
            "狂戦士としてレベル40に到達した",
            "Reached level 40 as Berserker",
            AC::CHARACTER,
            ADiff::HARD,
            40) },

    { AT::SMITH_TITLE_L40,
        std::make_shared<AD>(
            AT::SMITH_TITLE_L40,
            "魂を鍛えし者",
            "Soul smith",
            "鍛冶師としてレベル40に到達した",
            "Reached level 40 as Weaponsmith",
            AC::CHARACTER,
            ADiff::HARD,
            40) },

    { AT::MIRROR_MASTER_TITLE_L40,
        std::make_shared<AD>(
            AT::MIRROR_MASTER_TITLE_L40,
            "鏡の皇帝",
            "Mirror Emperor",
            "鏡使いとしてレベル40に到達した",
            "Reached level 40 as Mirror-Master",
            AC::CHARACTER,
            ADiff::HARD,
            40) },

    { AT::NINJA_TITLE_L40,
        std::make_shared<AD>(
            AT::NINJA_TITLE_L40,
            "闇の一撃",
            "Shadowstrike",
            "忍者としてレベル40に到達した",
            "Reached level 40 as Ninja",
            AC::CHARACTER,
            ADiff::HARD,
            40) },

    { AT::SNIPER_TITLE_L40,
        std::make_shared<AD>(
            AT::SNIPER_TITLE_L40,
            "男爵",
            "Baron",
            "スナイパーとしてレベル40に到達した",
            "Reached level 40 as Sniper",
            AC::CHARACTER,
            ADiff::HARD,
            40) },

    { AT::ELEMENTALIST_TITLE_L40,
        std::make_shared<AD>(
            AT::ELEMENTALIST_TITLE_L40,
            "魔道師",
            "Sorcerer",
            "元素使いとしてレベル40に到達した",
            "Reached level 40 as Elementalist",
            AC::CHARACTER,
            ADiff::HARD,
            40) },

    // レベル50（称号10段階目・最高位）
    { AT::WARRIOR_TITLE_MAX,
        std::make_shared<AD>(
            AT::WARRIOR_TITLE_MAX,
            "君主",
            "Lord",
            "戦士としてレベル50に到達した",
            "Reached level 50 as Warrior",
            AC::CHARACTER,
            ADiff::HARD,
            50) },

    { AT::MAGE_TITLE_MAX,
        std::make_shared<AD>(
            AT::MAGE_TITLE_MAX,
            "大魔道師",
            "Archmage",
            "メイジとしてレベル50に到達した",
            "Reached level 50 as Mage",
            AC::CHARACTER,
            ADiff::HARD,
            50) },

    { AT::PRIEST_TITLE_MAX,
        std::make_shared<AD>(
            AT::PRIEST_TITLE_MAX,
            "教皇",
            "Pope",
            "プリーストとしてレベル50に到達した",
            "Reached level 50 as Priest",
            AC::CHARACTER,
            ADiff::HARD,
            50) },

    { AT::ROGUE_TITLE_MAX,
        std::make_shared<AD>(
            AT::ROGUE_TITLE_MAX,
            "頭領",
            "Guildmaster",
            "盗賊としてレベル50に到達した",
            "Reached level 50 as Rogue",
            AC::CHARACTER,
            ADiff::HARD,
            50) },

    { AT::RANGER_TITLE_MAX,
        std::make_shared<AD>(
            AT::RANGER_TITLE_MAX,
            "野伏の総領",
            "Ranger Lord",
            "レンジャーとしてレベル50に到達した",
            "Reached level 50 as Ranger",
            AC::CHARACTER,
            ADiff::HARD,
            50) },

    { AT::PALADIN_TITLE_MAX,
        std::make_shared<AD>(
            AT::PALADIN_TITLE_MAX,
            "聖騎士団長",
            "Paladin Lord",
            "パラディンとしてレベル50に到達した",
            "Reached level 50 as Paladin",
            AC::CHARACTER,
            ADiff::HARD,
            50) },

    { AT::WARRIOR_MAGE_TITLE_MAX,
        std::make_shared<AD>(
            AT::WARRIOR_MAGE_TITLE_MAX,
            "知識の守護者",
            "Wizard Lord",
            "魔法戦士としてレベル50に到達した",
            "Reached level 50 as Warrior-Mage",
            AC::CHARACTER,
            ADiff::HARD,
            50) },

    { AT::CHAOS_WARRIOR_TITLE_MAX,
        std::make_shared<AD>(
            AT::CHAOS_WARRIOR_TITLE_MAX,
            "混沌の王者",
            "Chaos Lord",
            "混沌の戦士としてレベル50に到達した",
            "Reached level 50 as Chaos-Warrior",
            AC::CHARACTER,
            ADiff::HARD,
            50) },

    { AT::MONK_TITLE_MAX,
        std::make_shared<AD>(
            AT::MONK_TITLE_MAX,
            "拳神",
            "Grand Master",
            "修行僧としてレベル50に到達した",
            "Reached level 50 as Monk",
            AC::CHARACTER,
            ADiff::HARD,
            50) },

    { AT::MINDCRAFTER_TITLE_MAX,
        std::make_shared<AD>(
            AT::MINDCRAFTER_TITLE_MAX,
            "精神の支配者",
            "Mindmaster",
            "超能力者としてレベル50に到達した",
            "Reached level 50 as Mindcrafter",
            AC::CHARACTER,
            ADiff::HARD,
            50) },

    { AT::HIGH_MAGE_TITLE_MAX,
        std::make_shared<AD>(
            AT::HIGH_MAGE_TITLE_MAX,
            "大魔道師",
            "Archmage",
            "ハイ=メイジとしてレベル50に到達した",
            "Reached level 50 as High-Mage",
            AC::CHARACTER,
            ADiff::HARD,
            50) },

    { AT::TOURIST_TITLE_MAX,
        std::make_shared<AD>(
            AT::TOURIST_TITLE_MAX,
            "スペランカー",
            "Spelunker",
            "観光客としてレベル50に到達した",
            "Reached level 50 as Tourist",
            AC::CHARACTER,
            ADiff::VERY_HARD,
            60) },

    { AT::IMITATOR_TITLE_MAX,
        std::make_shared<AD>(
            AT::IMITATOR_TITLE_MAX,
            "えらい",
            "Great man",
            "ものまね師としてレベル50に到達した",
            "Reached level 50 as Imitator",
            AC::CHARACTER,
            ADiff::HARD,
            50) },

    { AT::BEASTMASTER_TITLE_MAX,
        std::make_shared<AD>(
            AT::BEASTMASTER_TITLE_MAX,
            "ドラゴン使い",
            "Dragon Master",
            "魔獣使いとしてレベル50に到達した",
            "Reached level 50 as BeastMaster",
            AC::CHARACTER,
            ADiff::HARD,
            50) },

    { AT::SORCERER_TITLE_MAX,
        std::make_shared<AD>(
            AT::SORCERER_TITLE_MAX,
            "大魔道師",
            "Archmage",
            "スペルマスターとしてレベル50に到達した",
            "Reached level 50 as Sorcerer",
            AC::CHARACTER,
            ADiff::VERY_HARD,
            60) },

    { AT::ARCHER_TITLE_MAX,
        std::make_shared<AD>(
            AT::ARCHER_TITLE_MAX,
            "領主",
            "Lord",
            "アーチャーとしてレベル50に到達した",
            "Reached level 50 as Archer",
            AC::CHARACTER,
            ADiff::HARD,
            50) },

    { AT::MAGIC_EATER_TITLE_MAX,
        std::make_shared<AD>(
            AT::MAGIC_EATER_TITLE_MAX,
            "全てを知る者",
            "Almighty",
            "魔道具術師としてレベル50に到達した",
            "Reached level 50 as Magic-Eater",
            AC::CHARACTER,
            ADiff::HARD,
            50) },

    { AT::BARD_TITLE_MAX,
        std::make_shared<AD>(
            AT::BARD_TITLE_MAX,
            "マスター",
            "Master Harper",
            "吟遊詩人としてレベル50に到達した",
            "Reached level 50 as Bard",
            AC::CHARACTER,
            ADiff::HARD,
            50) },

    { AT::RED_MAGE_TITLE_MAX,
        std::make_shared<AD>(
            AT::RED_MAGE_TITLE_MAX,
            "知識の守護者",
            "Wizard Lord",
            "赤魔道師としてレベル50に到達した",
            "Reached level 50 as Red-Mage",
            AC::CHARACTER,
            ADiff::HARD,
            50) },

    { AT::SAMURAI_TITLE_MAX,
        std::make_shared<AD>(
            AT::SAMURAI_TITLE_MAX,
            "剣神",
            "Grand Master",
            "剣術家としてレベル50に到達した",
            "Reached level 50 as Samurai",
            AC::CHARACTER,
            ADiff::HARD,
            50) },

    { AT::FORCETRAINER_TITLE_MAX,
        std::make_shared<AD>(
            AT::FORCETRAINER_TITLE_MAX,
            "拳神",
            "Grand Master",
            "練気術師としてレベル50に到達した",
            "Reached level 50 as ForceTrainer",
            AC::CHARACTER,
            ADiff::HARD,
            50) },

    { AT::BLUE_MAGE_TITLE_MAX,
        std::make_shared<AD>(
            AT::BLUE_MAGE_TITLE_MAX,
            "大魔道師",
            "Archmage",
            "青魔道師としてレベル50に到達した",
            "Reached level 50 as Blue-Mage",
            AC::CHARACTER,
            ADiff::HARD,
            50) },

    { AT::CAVALRY_TITLE_MAX,
        std::make_shared<AD>(
            AT::CAVALRY_TITLE_MAX,
            "領主",
            "Lord",
            "騎兵としてレベル50に到達した",
            "Reached level 50 as Cavalry",
            AC::CHARACTER,
            ADiff::HARD,
            50) },

    { AT::BERSERKER_TITLE_MAX,
        std::make_shared<AD>(
            AT::BERSERKER_TITLE_MAX,
            "怒りの化身",
            "God of Rage",
            "狂戦士としてレベル50に到達した",
            "Reached level 50 as Berserker",
            AC::CHARACTER,
            ADiff::VERY_HARD,
            60) },

    { AT::SMITH_TITLE_MAX,
        std::make_shared<AD>(
            AT::SMITH_TITLE_MAX,
            "全を鍛えし者",
            "AlmightySmith",
            "鍛冶師としてレベル50に到達した",
            "Reached level 50 as Weaponsmith",
            AC::CHARACTER,
            ADiff::HARD,
            50) },

    { AT::MIRROR_MASTER_TITLE_MAX,
        std::make_shared<AD>(
            AT::MIRROR_MASTER_TITLE_MAX,
            "ラフノール王",
            "Ruffnor King",
            "鏡使いとしてレベル50に到達した",
            "Reached level 50 as Mirror-Master",
            AC::CHARACTER,
            ADiff::HARD,
            50) },

    { AT::NINJA_TITLE_MAX,
        std::make_shared<AD>(
            AT::NINJA_TITLE_MAX,
            "死の長き腕",
            "Death Lord",
            "忍者としてレベル50に到達した",
            "Reached level 50 as Ninja",
            AC::CHARACTER,
            ADiff::HARD,
            50) },

    { AT::SNIPER_TITLE_MAX,
        std::make_shared<AD>(
            AT::SNIPER_TITLE_MAX,
            "領主",
            "Lord",
            "スナイパーとしてレベル50に到達した",
            "Reached level 50 as Sniper",
            AC::CHARACTER,
            ADiff::HARD,
            50) },

    { AT::ELEMENTALIST_TITLE_MAX,
        std::make_shared<AD>(
            AT::ELEMENTALIST_TITLE_MAX,
            "大魔道師",
            "Archmage",
            "元素使いとしてレベル50に到達した",
            "Reached level 50 as Elementalist",
            AC::CHARACTER,
            ADiff::HARD,
            50) },

    // アイテム系
    { AT::FIRST_ARTIFACT,
        std::make_shared<AD>(
            AT::FIRST_ARTIFACT,
            "トレジャーハンター",
            "Treasure Hunter",
            "初めて★を入手した",
            "Found your first artifact",
            AC::COLLECTION,
            ADiff::EASY,
            10) },

    { AT::COLLECT_10_ARTIFACTS,
        std::make_shared<AD>(
            AT::COLLECT_10_ARTIFACTS,
            "コレクター",
            "Collector",
            "10個の★を入手した",
            "Collected 10 artifacts",
            AC::COLLECTION,
            ADiff::NORMAL,
            25) },

    // 特殊系
    { AT::WIN_GAME,
        std::make_shared<AD>(
            AT::WIN_GAME,
            "世界の救世主",
            "Savior of the World",
            "ゲームをクリアした",
            "Won the game",
            AC::SPECIAL,
            ADiff::VERY_HARD,
            100) },

    { AT::FIRST_DEATH,
        std::make_shared<AD>(
            AT::FIRST_DEATH,
            "永遠の眠り",
            "Eternal Sleep",
            "初めて死亡した",
            "Died for the first time",
            AC::SPECIAL,
            ADiff::TRIVIAL,
            5) },
};

const std::shared_ptr<AchievementDefinition> &get_achievement_definition(AchievementType type)
{
    static std::shared_ptr<AchievementDefinition> null_def;

    auto it = achievement_definitions.find(type);
    if (it == achievement_definitions.end()) {
        return null_def;
    }

    return it->second;
}
