#pragma once

enum player_personality_type {
    PERSONALITY_NONE = -1,
    PERSONALITY_ORDINARY = 0,
    PERSONALITY_MIGHTY = 1,
    PERSONALITY_SHREWD = 2,
    PERSONALITY_PIOUS = 3,
    PERSONALITY_NIMBLE = 4,
    PERSONALITY_FEARLESS = 5,
    PERSONALITY_COMBAT = 6,
    PERSONALITY_LAZY = 7,
    PERSONALITY_SEXY = 8,
    PERSONALITY_LUCKY = 9,
    PERSONALITY_PATIENT = 10,
    PERSONALITY_MUNCHKIN = 11,
    PERSONALITY_CHARGEMAN = 12,
    PERSONALITY_TOUGH = 13,
    PERSONALITY_SUSHI_EATER = 14,
    PERSONALITY_MESUGAKI = 15,
    PERSONALITY_EMPTY = 16, //!< 無心。プレイヤーは選択不能。EMPTY_MIND モンスター専用
    MAX_SELECTABLE_PERSONALITIES = 16, //!< プレイヤーが選択可能な性格数 (PERSONALITY_EMPTY を除く)
    MAX_PERSONALITIES = 17,
};
