#pragma once

#include <string_view>

class CreatureEntity;
class ItemEntity;
class PlayerType;
bool activate_sunlight(CreatureEntity &creature);
bool activate_confusion(CreatureEntity &creature);
bool activate_banish_evil(CreatureEntity &creature);
bool activate_scare(CreatureEntity &creature);
bool activate_aggravation(CreatureEntity &creature, const ItemEntity &item, std::string_view name);
bool activate_stone_mud(CreatureEntity &creature);
bool activate_judgement(CreatureEntity &creature, std::string_view name);
bool activate_telekinesis(CreatureEntity &creature, std::string_view name);
bool activate_unique_detection(CreatureEntity &creature);
bool activate_dispel_curse(CreatureEntity &creature, std::string_view name);
bool activate_cure_lw(CreatureEntity &creature);
bool activate_grand_cross(CreatureEntity &creature);
bool activate_call_chaos(CreatureEntity &creature);
bool activate_dispel_evil(CreatureEntity &creature);
bool activate_dispel_good(CreatureEntity &creature);
bool activate_all_monsters_detection(CreatureEntity &creature);
bool activate_all_detection(CreatureEntity &creature);
bool activate_extra_detection(CreatureEntity &creature);
bool activate_fully_identification(CreatureEntity &creature);
bool activate_identification(CreatureEntity &creature);
bool activate_pesticide(CreatureEntity &creature);
bool activate_whirlwind(CreatureEntity &creature);
bool activate_blinding_light(CreatureEntity &creature, std::string_view name);
bool activate_sleep(CreatureEntity &creature);
bool activate_door_destroy(CreatureEntity &creature);
bool activate_earthquake(CreatureEntity &creature);
bool activate_recharge(CreatureEntity &creature);
bool activate_recharge_extra(CreatureEntity &creature, std::string_view name);
bool activate_shikofumi(CreatureEntity &creature);
bool activate_terror(CreatureEntity &creature);
bool activate_map_light(CreatureEntity &creature);
bool activate_exploding_rune(CreatureEntity &creature);
bool activate_protection_rune(CreatureEntity &creature);
bool activate_protection_elbereth(CreatureEntity &creature);
bool activate_light(CreatureEntity &creature, std::string_view name);
bool activate_recall(CreatureEntity &creature);
bool activate_tree_creation(CreatureEntity &creature, const ItemEntity &item, std::string_view name);
bool activate_animate_dead(CreatureEntity &creature, const ItemEntity &item);
bool activate_detect_treasure(CreatureEntity &creature);
bool activate_create_ammo(CreatureEntity &creature);
bool activate_dispel_magic(CreatureEntity &creature);
bool activate_huge_stinking_storm(CreatureEntity &creature);
bool activate_whistle(CreatureEntity &creature, const ItemEntity &item);
