#pragma once

enum class MonsterKindType {
    UNIQUE = 0,
    NONLIVING = 1,
    HUMAN = 2,
    QUANTUM = 3,
    ORC = 4,
    TROLL = 5,
    GIANT = 6,
    DRAGON = 7,
    DEMON = 8,
    AMBERITE = 9,
    ANGEL = 10,
    EVIL = 11,
    GOOD = 12,
    ANIMAL = 13,
    UNDEAD = 14,
    ELDRAZI = 15,
    ELF = 16,
    DWARF = 17,
    HOBBIT = 18,
    QUYLTHLUG = 19,
    SPIDER = 20,
    NASTY = 21,
    JOKE = 22,
    YAKUZA = 23,
    NINJA = 24,
    SUMOU_WRESTLER = 25,
    WARRIOR = 26,
    ROGUE = 27,
    MAGE = 28,
    PRIEST = 29,
    PALADIN = 30,
    RANGER = 31,
    SAMURAI = 32,
    KARATEKA = 33,
    HOMO_SEXUAL = 34,
    TANK = 35,
    HENTAI = 36,
    ELEMENTAL = 37,
    GOLEM = 38,
    PUYO = 39,
    ROBOT = 40,
    YAZYU = 41,
    SKELETON = 42,
    DOG = 43,
    CAT = 44,
    MONKEY_SPACE = 45, // 猿空間
    MALE = 46,
    FEMALE = 47,
    CHOASIAN = 48, // 混沌の王族
    ZOMBIE = 49, // ゾンビ
    INSECT = 50, // 昆虫
    CANCER = 51, // カニ
    FUNGAS = 52, // 菌類
    TURTLE = 53, // 亀
    MIMIC = 54, // ミミック
    IXITXACHITL = 55, // イクシツザチトル
    NAGA = 56, // ナーガ
    PERVERT = 57, // 変質者
    SOLDIER = 58,
    APE = 59, // 類人猿
    HORSE = 60, // 馬
    FROG = 61, // カエル
    BEHOLDER = 62, // ビホルダー
    YEEK = 63, // イーク
    AQUATIC_MAMMAL = 64, // 水棲哺乳類
    FISH = 65, // 魚類
    BIRD = 66, // 鳥
    WALL = 67, // 壁
    PLANT = 68, // 植物
    FUNGUS = 69, // 菌類
    SNAKE = 70, // 蛇
    FAIRY = 71, // 妖精
    VAMPIRE = 72, // 吸血鬼
    BEAR = 73, // 熊
    VORTEX = 74, // ボルテックス
    OOZE = 75, // ウーズ
    DINOSAUR = 76, // 恐竜
    LICH = 77, // リッチ
    GHOST = 78, // 幽霊
    BERSERK = 79, // 狂戦士
    EXPLOSIVE = 80, // 爆発物
    RAT = 81, // ネズミ
    MINOTAUR = 82, // ミノタウロス
    SKAVEN = 83, // スケイヴン
    KOBOLD = 84, // コボルド
    OGRE = 85, // オーガ
    MAX,
};
